FROM apache/airflow:2.8.4
USER root
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean
USER airflow
HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD [ "executable" ]